# Site Settings
title: Henryworld | Developer note
email: jymk04130@gmail.com
description: Blog for Developing AI & BigData.
baseurl:  # the subpath of your site, e.g. /blog
url: "https://github.com/jooyounghun" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: jooyounghun
user_description: Undergraduate Stu Kyung Hee Unv Major cs.
disqus_username: henry

# Social Media
# Remove the item if you don't need it
github_username: jooyounghun
facebook_username: 주영훈
instagram_username: younghundiy25
linkedin_username: younghun joo

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
